// Code generated by MockGen. DO NOT EDIT.
// Source: internal/developer/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	model "todo-planner/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetAllDevelopers mocks base method.
func (m *MockIRepository) GetAllDevelopers() ([]model.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDevelopers")
	ret0, _ := ret[0].([]model.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDevelopers indicates an expected call of GetAllDevelopers.
func (mr *MockIRepositoryMockRecorder) GetAllDevelopers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDevelopers", reflect.TypeOf((*MockIRepository)(nil).GetAllDevelopers))
}

// SaveDevelopers mocks base method.
func (m *MockIRepository) SaveDevelopers(developers []model.Developer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDevelopers", developers)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDevelopers indicates an expected call of SaveDevelopers.
func (mr *MockIRepositoryMockRecorder) SaveDevelopers(developers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDevelopers", reflect.TypeOf((*MockIRepository)(nil).SaveDevelopers), developers)
}
