// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"todo-planner/infrastructure"
	"todo-planner/internal/task"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	config, err := infrastructure.NewConfig()
	if err != nil {
		return nil, err
	}
	iLogger, err := infrastructure.NewLogger()
	if err != nil {
		return nil, err
	}
	iDatabase := infrastructure.NewDatabase(config)
	iRepository := task.NewRepository(iDatabase, iLogger)
	iServiceCaller := task.NewServiceCaller(config, iLogger)
	iService := task.NewService(iRepository, iServiceCaller, iDatabase, iLogger)
	application := &Application{
		Config:      config,
		Logger:      iLogger,
		Database:    iDatabase,
		TaskService: iService,
	}
	return application, nil
}
